# Generated by Django 3.1.7 on 2021-06-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_fname', models.CharField(max_length=50)),
                ('c_lname', models.CharField(max_length=45)),
                ('c_email', models.CharField(max_length=50)),
                ('c_subject', models.CharField(max_length=45)),
                ('c_message', models.CharField(max_length=30)),
            ],
        ),
    ]
